server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
    datasource:
      jndi-name: java:comp/env/jdbc/myDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/dev_db
      username: dev_user
      password: dev_password

p6spy:
  config:
    log-message-format: egovframework.config.P6SpyConfig
    include-categories: statement,resultset

logging:
  level:
    root: info
    egovframework: debug
    edms: debug
    p6spy: debug
    jdbc:
      error: error
      connection: error
      audit: error
      sqltiming: error
    jdbc.sqlonly: off
    jdbc.resultsettable: info
  config: classpath:log4j2.xml

  #ai
  ollama:
    base-url: http://localhost:11434
    model: gpt-oss:20b
    max-memory-size: 10485760  # 10MB
    api:
      chat: /api/chat