server:
  port: 8080

# 수동 Bean이 자동 Bean을 오버라이딩하게 설정
spring:
  main:
    allow-bean-definition-overriding: true

  # open-in-view(혹은 Open-Session-In-View(OSIV))
  # true(기본값) : 사용자에게 응답 또는 view가 렌더링될 때까지 영속성 컨텍스트 유지
  # false : 트랜젝션이 종료될 때 영속성 컨텍스트 종료
  jpa:
    open-in-view: false

  # 1. 타임리프 엔진을 완전히 끕니다.
  thymeleaf:
    enabled: false

  # 2. JSP 경로와 확장자를 지정합니다.
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

# 로깅 설정 추가
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO